import { createContext, useState } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('ES');

  const translations = {
    ES: {
      home: 'Inicio',
      national: 'Paquetes Nacionales',
      international: 'Paquetes Internacionales',
      flights: 'Pasajes',
      insurance: 'Seguros',
      concerts: 'Conciertos',
      about: 'Nosotros',
      discoverWorld: 'Descubre el mundo con Sami Sisa Expeditions',
      uniqueExpeditions: 'Expediciones únicas por Sudamérica. Paisajes espectaculares, aventuras inolvidables y experiencias transformadoras te esperan.',
      explorePackages: 'Explorar Paquetes',
      viewTestimonials: 'Ver Testimonios',
      nationalPackagesTitle: 'Paquetes Nacionales',
      nationalPackagesDesc: 'Descubre las maravillas de Sudamérica. Desde los desiertos más espectaculares hasta antiguos sitios arqueológicos.',
      internationalPackagesTitle: 'Paquetes Internacionales',
      internationalPackagesDesc: 'Explora destinos de ensueño alrededor del mundo. Experiencias premium que transformarán tus vacaciones.',
      airwaysTitle: 'Pasajes Aéreos',
      airwaysDesc: 'Vuelos directos a los destinos más hermosos de Sudamérica y el Caribe.',
      searchFlight: 'Busca tu vuelo',
      insureTitle: 'Seguro de Viajes',
      insureDesc: 'Viaja con seguridad. Cobertura médica completa y asistencia en el mundo entero.',
      choosePlan: 'Elige tu plan de protección',
      concertsTitle: '🎵 Conciertos & Experiencias',
      concertsDesc: 'Vive la música en directo con paquetes premium que incluyen alojamiento, traslados y experiencias VIP.',
      aboutTitle: 'Sobre Nosotros',
      aboutMission: 'Nuestra Misión',
      aboutMissionDesc: 'En Sami Sisa Expeditions, creemos que viajar transforma vidas. Nos dedicamos a crear experiencias auténticas y memorables que conecten a nuestros clientes con la belleza natural y cultural de Sudamérica.',
      aboutWhy: '¿Por Qué Elegirnos?',
      aboutExperts: 'Expertos locales con conocimiento profundo de cada destino',
      aboutPersonalized: 'Paquetes personalizados adaptados a tus intereses',
      aboutSupport: 'Soporte 24/7 en español, inglés y portugués',
      contact: 'Contacto',
    },
    EN: {
      home: 'Home',
      national: 'National Packages',
      international: 'International Packages',
      flights: 'Flights',
      insurance: 'Insurance',
      concerts: 'Concerts',
      about: 'About',
      discoverWorld: 'Discover the world with Sami Sisa Expeditions',
      uniqueExpeditions: 'Unique expeditions across South America. Spectacular landscapes, unforgettable adventures and transformative experiences await you.',
      explorePackages: 'Explore Packages',
      viewTestimonials: 'View Testimonials',
      nationalPackagesTitle: 'National Packages',
      nationalPackagesDesc: 'Discover the wonders of South America. From the most spectacular deserts to ancient archaeological sites.',
      internationalPackagesTitle: 'International Packages',
      internationalPackagesDesc: 'Explore dream destinations around the world. Premium experiences that will transform your vacation.',
      airwaysTitle: 'Flights',
      airwaysDesc: 'Direct flights to the most beautiful destinations in South America and the Caribbean.',
      searchFlight: 'Search your flight',
      insureTitle: 'Travel Insurance',
      insureDesc: 'Travel safely. Complete medical coverage and assistance around the world.',
      choosePlan: 'Choose your protection plan',
      concertsTitle: '🎵 Concerts & Experiences',
      concertsDesc: 'Experience live music with premium packages that include accommodation, transfers and VIP experiences.',
      aboutTitle: 'About Us',
      aboutMission: 'Our Mission',
      aboutMissionDesc: 'At Sami Sisa Expeditions, we believe that travel transforms lives. We are dedicated to creating authentic and memorable experiences that connect our clients with the natural and cultural beauty of South America.',
      aboutWhy: 'Why Choose Us?',
      aboutExperts: 'Local experts with deep knowledge of each destination',
      aboutPersonalized: 'Customized packages tailored to your interests',
      aboutSupport: '24/7 support in Spanish, English and Portuguese',
      contact: 'Contact',
    },
    PT: {
      home: 'Início',
      national: 'Pacotes Nacionais',
      international: 'Pacotes Internacionais',
      flights: 'Voos',
      insurance: 'Seguros',
      concerts: 'Concertos',
      about: 'Sobre',
      discoverWorld: 'Descubra o mundo com Sami Sisa Expeditions',
      uniqueExpeditions: 'Expedições únicas pela América do Sul. Paisagens espetaculares, aventuras inesquecíveis e experiências transformadoras aguardam você.',
      explorePackages: 'Explorar Pacotes',
      viewTestimonials: 'Ver Depoimentos',
      nationalPackagesTitle: 'Pacotes Nacionais',
      nationalPackagesDesc: 'Descubra as maravilhas da América do Sul. Desde os desertos mais espetaculares até sítios arqueológicos antigos.',
      internationalPackagesTitle: 'Pacotes Internacionais',
      internationalPackagesDesc: 'Explore destinos de sonho em todo o mundo. Experiências premium que transformarão suas férias.',
      airwaysTitle: 'Voos',
      airwaysDesc: 'Voos diretos para os destinos mais bonitos da América do Sul e do Caribe.',
      searchFlight: 'Procure seu voo',
      insureTitle: 'Seguro de Viagem',
      insureDesc: 'Viaje com segurança. Cobertura médica completa e assistência em todo o mundo.',
      choosePlan: 'Escolha seu plano de proteção',
      concertsTitle: '🎵 Concertos & Experiências',
      concertsDesc: 'Experimente música ao vivo com pacotes premium que incluem hospedagem, transferências e experiências VIP.',
      aboutTitle: 'Sobre Nós',
      aboutMission: 'Nossa Missão',
      aboutMissionDesc: 'Na Sami Sisa Expeditions, acreditamos que viajar transforma vidas. Nos dedicamos a criar experiências autênticas e memoráveis que conectem nossos clientes com a beleza natural e cultural da América do Sul.',
      aboutWhy: 'Por Que Nos Escolher?',
      aboutExperts: 'Especialistas locais com conhecimento profundo de cada destino',
      aboutPersonalized: 'Pacotes personalizados adaptados aos seus interesses',
      aboutSupport: 'Suporte 24/7 em espanhol, inglês e português',
      contact: 'Contato',
    },
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
